name: Project Publishing
permissions:
  contents: write
on:
  push:
    paths: [ 'Avalonia.FluentUI/**', '**/Publish.yml' ]
env:
  PROJECT_NAME: Avalonia.FluentUI
  TFM: net9.0
jobs:
  publish:
    strategy:
      matrix:
        include:
          - platform: windows-latest
            runtime: win-x64
          - platform: ubuntu-latest
            runtime: linux-x64
          - platform: macos-latest
            runtime: osx-x64
          - platform: macos-latest
            runtime: osx-arm64
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@main
      - uses: actions/cache@main
        with:
          path: ~/.nuget/packages
          key: nuget-cache-${{ matrix.platform }}

      - if: matrix.platform != 'macos-latest'
        run: dotnet publish -r ${{ matrix.runtime }} -p:PublishAot=true

      - if: matrix.platform == 'macos-latest'
        run: |
          dotnet publish -t:BundleApp -r ${{ matrix.runtime }} -p:PublishAot=true -p:UseAppHost=true
          cd ${{ env.PROJECT_NAME }}/bin/Release/${{ env.TFM }}/${{ matrix.runtime }}/publish
          chmod +x ${{ env.PROJECT_NAME }}.app/Contents/MacOS/${{ env.PROJECT_NAME }}
          codesign --force --deep --sign - ${{ env.PROJECT_NAME }}.app
          codesign --verify --verbose ${{ env.PROJECT_NAME }}.app
          
      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
    
      - if: matrix.platform == 'ubuntu-latest'
        working-directory: ${{ env.PROJECT_NAME }}/bin/Release/${{ env.TFM }}/${{ matrix.runtime }}/publish
        run: zip -r ../../Release-${{ matrix.runtime }}.zip . -x '*.dbg'

      - if: matrix.platform == 'macos-latest'
        working-directory: ${{ env.PROJECT_NAME }}/bin/Release/${{ env.TFM }}/${{ matrix.runtime }}/publish
        run: zip -r ../../Release-${{ matrix.runtime }}.zip *.app -x '*.dSYM/*'

      - if: matrix.platform == 'windows-latest'
        working-directory: ${{ env.PROJECT_NAME }}/bin/Release/${{ env.TFM }}/${{ matrix.runtime }}/publish
        run: |
          $files = Get-ChildItem -Recurse -File | Where-Object { $_.Extension -notin '.pdb' }
          Compress-Archive -Path $files.FullName -DestinationPath ..\..\Release-${{ matrix.runtime }}.zip -CompressionLevel Optimal

      - uses: softprops/action-gh-release@master
        with:
          tag_name: action
          prerelease: true
          overwrite_files: true
          files: '**/*.zip'